# run a node.js script to use code from semantic-release
after_success:
  - node release.js
cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.yarn-cache
# yarn is used to run to release script which runs part of the node.js semantic-release library
install:
  - yarn
jdk:
  - oraclejdk8
language: java
notifications:
  email: false
script:
  - mvn package
sudo: false
