# run a node.js script to use code from semantic-release
after_success:
  - yarn global add @conveyal/maven-semantic-release && maven-semantic-release --debug
cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.yarn-cache
install: true
jdk:
  - oraclejdk8
language: java
notifications:
  email: false
script:
  - mvn package
sudo: false
before_install: |
  # only install signing keys under the same circumstances we do a mvn deploy later
  if [[ "$TRAVIS_PULL_REQUEST" = false ]] && [[ "$TRAVIS_BRANCH" = master ]]; then
    openssl aes-256-cbc -K $encrypted_319571283a54_key -iv $encrypted_319571283a54_iv -in maven-artifact-signing-key.asc.enc -out maven-artifact-signing-key.asc -d
    gpg --import --batch maven-artifact-signing-key.asc
  fi
